apiVersion: v1
kind: Service
metadata:
  name: global-commerce-order

spec:
  type: ClusterIP

  selector:
    app: global-commerce-order

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080